name: Automated E2E Testing
on: 
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main
        
      - name: Write the cypress.env.json file
        run: |
          echo '{
            "user-email": "'${{ secrets.USER_EMAIL }}'",
            "user-password": "'${{ secrets.USER_PASSWORD }}'",
            "wrong-user": "'${{ secrets.WRONG_USER }}'",
            "wrong-password": "'${{ secrets.WRONG_PASSWORD }}'"
          }' > cypress.env.json
          
      - name: run cypress tests with electron
        uses: cypress-io/github-action@v4
        with:
          browser: electron
